name: Compile OpenWrt

on:
  push:
    branches:
      - main  # 当 main 分支有推送时触发
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 触发编译任务，可以根据需要调整

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up OpenWrt
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev \
          libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev \
          libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 \
          python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
          uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          
          git clone https://github.com/coolsnowwolf/lede
          
          cd lede
          
          echo "src-git small https://github.com/kenzok8/small" >> "feeds.conf.default"
          echo "src-git kenzo https://github.com/kenzok8/openwrt-packages" >> "feeds.conf.default"
          echo "src-git helloworld https://github.com/fw876/helloworld" >> "feeds.conf.default"
          echo "src-git netspeedtest  https://github.com/sirpdboy/netspeedtest" >> "feeds.conf.default"
          echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> "feeds.conf.default"
          echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main" >> "feeds.conf.default"
          
          git clone https://github.com/esirplayground/luci-app-poweroff package/lean/luci-app-poweroff
          
          # 如果需要选择特定分支，可以使用以下命令
          # git checkout <branch_name>

          # 更新 feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure OpenWrt
        env:
          CONFIG_FILE: '.config'
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE lede/.config
          cd lede
          make defconfig
          
          # 在这里可以手动配置 OpenWrt，选择目标硬件平台、需要的软件包等

      - name: Compile OpenWrt
        run: |
          cd lede
          make download -j8
          make V=s -j1

      - name: Package Firmware
        run: |
          cd openwrt/bin/targets/*/*
          # 这里可以添加组织文件、生成固件的步骤，例如压缩、生成 SHA256 校验和等操作

      - name: Upload Firmware
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: openwrt/bin/targets/*/*.zip  # 替换为实际的固件文件路径
          asset_name: openwrt-firmware.zip  # 替换为实际的固件文件名
          asset_content_type: application/zip
