name: Compile OpenWrt

on:
  push:
    branches:
      - main  # 当 main 分支有推送时触发
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 触发编译任务，可以根据需要调整

jobs:
  build:
    runs-on: ubuntu-20.04

    permissions:
      contents: write
    
    steps:
    - name: 检查项目分支
      uses: actions/checkout@main
      
    - name: 初始化编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: 清理磁盘空间(Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # when set to "true" but frees about 6 GB
        tool-cache: true
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: false
        dotnet: false
        haskell: false
        large-packages: false
        swap-storage: false
        
    - name: Download source code    
    
        git clone https://github.com/coolsnowwolf/lede
        
        cd lede
          
        echo "src-git small https://github.com/kenzok8/small" >> "feeds.conf.default"
        echo "src-git kenzo https://github.com/kenzok8/openwrt-packages" >> "feeds.conf.default"
        echo "src-git helloworld https://github.com/fw876/helloworld" >> "feeds.conf.default"
        echo "src-git netspeedtest  https://github.com/sirpdboy/netspeedtest" >> "feeds.conf.default"
        echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> "feeds.conf.default"
        echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main" >> "feeds.conf.default"
          
        git clone https://github.com/esirplayground/luci-app-poweroff package/lean/luci-app-poweroff
          
        # 如果需要选择特定分支，可以使用以下命令
        # git checkout <branch_name>

        # 更新 feeds
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure OpenWrt
        env:
          CONFIG_FILE: '.config'
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE lede/.config
          cd lede
          make defconfig
          
          # 在这里可以手动配置 OpenWrt，选择目标硬件平台、需要的软件包等

    - name: Compile OpenWrt
        run: |
          cd lede
          make download -j8
          make V=s -j1

    - name: Package Firmware
        run: |
          cd openwrt/bin/targets/*/*
          # 这里可以添加组织文件、生成固件的步骤，例如压缩、生成 SHA256 校验和等操作

    - name: 发布固件至Release
      uses: softprops/action-gh-release@master
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ env.FIRMWARE }}/*
        name: ${{ env.FILE_DATE }}-${{ env.OPENWRT_NAME }}-${{ env.UPLOAD_TAG_NAME }}-${{ env.EMMC_MHZ }}${{ env.EEPROM }}${{ env.WIFI_INTERFACE }}${{ env.BUILD_DOCKERMAN }}
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
